language: java
install: true

env:
  global:
    - HOME="OnlineShopSimulator"

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk11

notifications:
  email:
    recipients:
      - andrea.giuntini@stud.unifi.it
      - agemelli60@gmail.com
      - ale.venturi95@yahoo.it
    on_success: never # default: change
    on_failure: always # default: always
    
sonarqube:
  token: $SONAR_TOKEN

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script: cd $HOME/

script:
  - ./gradlew build --scan -s
  - ./gradlew sonarqube -Dsonar.login="3a59cd7138a693df1db4c23fc7aee8dbf818bf68"

after_success:
  - ./gradlew jacocoTestReport coveralls

